spring:
  profiles:
    # fixed-backoff, exponential-backoff, exponential-random-backoff
    active: fixed-backoff
  application:
    name: demo-client

server:
  port: 8080

ribbon:
  eureka:
    enabled: false
  eager-load:
    enabled: true
    clients: weather-service
  # Read timeout/Connect timeout used by Apache HttpClient
  # It seems that they are not supported by RestTemplate in Spring Cloud Netflix.
  # Github comment: "One thing that surprised us was that the ribbon setting for connection timeouts are NOT applied when using the rest template."
  # After I added timeouts to RestTemplate, requests have started timing out at expected intervals.
  #ReadTimeout: 1000
  #ConnectTimeout: 1000

weather-service:
  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:8082, http://localhost:8083
    ServerListRefreshInterval: 5000
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 1
    #You can also control whether just GET requests will be retried or whether all requests will be retried.
    OkToRetryOnAllOperations: true
    retryableStatusCodes: 500, 501, 502, 503, 504, 408
#    OkToRetryOnAllErrors: true
#    OkRetryOnConnectionErrors=true


# Classes defined in these properties have precedence over beans defined by using @RibbonClient(configuration=MyRibbonConfig.class)
#  and the defaults provided by Spring Cloud Netflix.

# <clientName>.ribbon.NFLoadBalancerClassName: Should implement ILoadBalancer
# <clientName>.ribbon.NFLoadBalancerRuleClassName: Should implement IRule
# <clientName>.ribbon.NFLoadBalancerPingClassName: Should implement IPing
# <clientName>.ribbon.NIWSServerListClassName: Should implement ServerList
# <clientName>.ribbon.NIWSServerListFilterClassName: Should implement ServerListFilter

